/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindingsIndexRouteImport } from './routes/findings/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as AuditsIndexRouteImport } from './routes/audits/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ContractsContractIdRouteImport } from './routes/contracts/$contractId'
import { Route as AuditsAuditIdRouteImport } from './routes/audits/$auditId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsAuditIdRoute = AuditsAuditIdRouteImport.update({
  id: '/audits/$auditId',
  path: '/audits/$auditId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/audits/': typeof AuditsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/findings/': typeof FindingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/audits': typeof AuditsIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/findings': typeof FindingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/audits/$auditId': typeof AuditsAuditIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/audits/': typeof AuditsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/findings/': typeof FindingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/memory'
    | '/settings'
    | '/audits/$auditId'
    | '/contracts/$contractId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/audits/'
    | '/contracts/'
    | '/findings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/memory'
    | '/settings'
    | '/audits/$auditId'
    | '/contracts/$contractId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/audits'
    | '/contracts'
    | '/findings'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/dashboard'
    | '/memory'
    | '/settings'
    | '/audits/$auditId'
    | '/contracts/$contractId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/audits/'
    | '/contracts/'
    | '/findings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  AuditsAuditIdRoute: typeof AuditsAuditIdRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$auditId': {
      id: '/audits/$auditId'
      path: '/audits/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuditsAuditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  AuditsAuditIdRoute: AuditsAuditIdRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  AuditsIndexRoute: AuditsIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  FindingsIndexRoute: FindingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
